 /*==============================================================*/
/* TEST AJOUT EQUIPE      : ok          hhh                        */
/*==============================================================*/
/*INSERT INTO EQUIPE (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE) 
VALUES (seq_id_equipe.NEXTVAL, 'Nouvelle Adresse', 5000);
INSERT INTO EQUIPE (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE) 
VALUES (seq_id_equipe.NEXTVAL, 'Nouvelle Adresse', 5070);
INSERT INTO EQUIPE (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE) 
VALUES (seq_id_equipe.NEXTVAL, 'Nouvelle Adresse', 5007);*/


/*==============================================================*/
/* Peuplement des tables                                        */
/*==============================================================*/
-- FOURNISEUR 
<<<<<<< HEAD
CREATE OR REPLACE PROCEDURE peupler_table_fournisseur AS
BEGIN
    DELETE FROM FOURNISSEUR;
    INSERT INTO FOURNISSEUR (ID_FOURNISSEUR, NOM_FOURNISSEUR) VALUES (1, 'Fournisseur 1');
    INSERT INTO FOURNISSEUR (ID_FOURNISSEUR, NOM_FOURNISSEUR) VALUES (2, 'Fournisseur 2');
    COMMIT; -- Valider les modifications
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK; 
        RAISE;
END peupler_table_fournisseur;
/
=======
INSERT INTO FOURNISSEUR (ID_FOURNISSEUR, NOM_FOURNISSEUR) VALUES (1, 'Pfizer');
INSERT INTO FOURNISSEUR (ID_FOURNISSEUR, NOM_FOURNISSEUR) VALUES (2, 'Siemens');
>>>>>>> 27b134b37b8832306bfe87ed1ecbf30eed5c474e

--STOCK
CREATE OR REPLACE PROCEDURE peupler_table_stock AS
BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO stock (id_stock, quantite_p384, quantite_p96, vol_dernier_tri_p384, vol_dernier_tri_p96)
        VALUES (i, ROUND(DBMS_RANDOM.VALUE(1, 100)), ROUND(DBMS_RANDOM.VALUE(1, 100)), ROUND(DBMS_RANDOM.VALUE(1, 100)), ROUND(DBMS_RANDOM.VALUE(1, 100)));
    END LOOP;
    COMMIT;
END;
/

--LOT
CREATE OR REPLACE PROCEDURE peupler_table_lot AS
BEGIN
    FOR i IN 1..10 LOOP 
        INSERT INTO lot (id_lot, id_stock, date_livraison_lot, nb_plaque)
        VALUES (i, ROUND(DBMS_RANDOM.VALUE(1, 10)), SYSDATE - i, 80); 
    END LOOP;
    COMMIT;
END;
/

--ACHETER
INSERT INTO ACHETER (ID_FOURNISSEUR, ID_LOT) VALUES (1, 1);
INSERT INTO ACHETER (ID_FOURNISSEUR, ID_LOT) VALUES (2, 2);

--EQUIPE
INSERT INTO EQUIPE_RECHERCHE  (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE)  
VALUES (SEQ_EQUIPE_ID.nextval, 'Rue Jean Monet', 5000);
INSERT INTO EQUIPE_RECHERCHE  (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE)  
VALUES (SEQ_EQUIPE_ID.nextval, 'Place Mermoz', 10000);

--CHERCHEUR
CREATE OR REPLACE PROCEDURE PEUPLE_CHERCHEUR(nb_lignes IN NUMBER) AS
    id_equipe EQUIPE.ID_EQUIPE%TYPE;
    nom_c VARCHAR2(25);
    prenom_c VARCHAR2(25);
BEGIN
    FOR i IN 1..nb_lignes LOOP
        SELECT ID_EQUIPE INTO id_equipe FROM (SELECT ID_EQUIPE FROM EQUIPE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
        nom_c := DBMS_RANDOM.STRING('A', 10);
        prenom_c := DBMS_RANDOM.STRING('A', 10);
        
        IF ASCII(SUBSTR(nom_c, 1, 1)) BETWEEN 97 AND 122 THEN
            nom_c := INITCAP(nom_c);
        END IF;
    
        IF ASCII(SUBSTR(prenom_c, 1, 1)) BETWEEN 97 AND 122 THEN
            prenom_c := INITCAP(prenom_c);
        END IF;
    
        INSERT INTO CHERCHEUR(ID_CHERCHEUR, ID_EQUIPE, NOM_CHERCHEUR, PRENOM_CHERCHEUR)
        VALUES(SEQ_ID_CHERCHEUR.NEXTVAL, id_equipe, nom_c, prenom_c);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
        ROLLBACK;
END;
/

EXEC PEUPLE_CHERCHEUR(10);


-- FACTURE
CREATE OR REPLACE PROCEDURE PEUPLE_FACTURE(nb_lignes IN NUMBER) DETERMINISTIC AS 
    id_equipe FACTURE.ID_EQUIPE%TYPE; 
BEGIN 
    FOR i IN 1..nb_lignes LOOP 
        SELECT ID_EQUIPE INTO id_equipe FROM (SELECT ID_EQUIPE FROM EQUIPE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1; 
        INSERT INTO FACTURE(ID_FACTURE, ID_EQUIPE, DATE_FACTURE, MONTANT_FACTURE) 
        VALUES(SEQ_ID_FACTURE.NEXTVAL, id_equipe, TRUNC(SYSDATE, 'MM'), ROUND(DBMS_RANDOM.VALUE(1000, 10000))); 
    END LOOP; 
    COMMIT; 
END;
/
EXEC PEUPLE_FACTURE(10);

--TECHNICIEN
CREATE OR REPLACE PROCEDURE peuple_technicien(nb_lignes IN NUMBER) DETERMINISTIC AS
    id_technicien TECHNICIEN.ID_TECHNICIEN%TYPE;
    id_equipe TECHNICIEN.ID_EQUIPE%TYPE;
    nom_technicien TECHNICIEN.NOM_TECHNICIEN%TYPE;
    prenom_technicien TECHNICIEN.PRENOM_TECHNICIEN%TYPE;
BEGIN
    FOR i IN 1..nb_lignes LOOP
        id_technicien := i;

        SELECT ID_EQUIPE INTO id_equipe
        FROM EQUIPE
        WHERE ROWNUM = 1
        ORDER BY DBMS_RANDOM.VALUE;

        nom_technicien := 'Technicien' || i;
        prenom_technicien := 'Prénom' || i;

        -- Insertion des valeurs générées dans la table TECHNICIEN
        INSERT INTO TECHNICIEN (ID_TECHNICIEN, ID_EQUIPE, NOM_TECHNICIEN, PRENOM_TECHNICIEN)
        VALUES (id_technicien, id_equipe, nom_technicien, prenom_technicien);
    END LOOP;
    COMMIT; 
END;
/

--APPAREIL
INSERT INTO APPAREIL (ID_APPAREIL, ID_LISTE, ETAT_APPAREIL, POSITION_APPAREIL) VALUES (seq_id_appareil.NEXTVAL, 1, 'Disponible', 1);

--EXPERIENCE
CREATE OR REPLACE PROCEDURE PEUPLE_EXPERIENCE(nb_lignes IN NUMBER) AS
    id_technicien EXPERIENCE.ID_TECHNICIEN%TYPE;
    id_chercheur EXPERIENCE.ID_CHERCHEUR%TYPE;
BEGIN
    FOR i IN 1..nb_lignes LOOP
        -- Sélectionner un ID_TECHNICIEN aléatoire
        SELECT ID_TECHNICIEN INTO id_technicien FROM TECHNICIEN ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY;
        -- Sélectionner un ID_CHERCHEUR aléatoire
        SELECT ID_CHERCHEUR INTO id_chercheur FROM CHERCHEUR ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROWS ONLY;
        
        -- Insérer des données aléatoires dans la table EXPERIENCE
        INSERT INTO EXPERIENCE(ID_EXPERIENCE, ID_TECHNICIEN, ID_CHERCHEUR, TYPE_EXPERIENCE, ETAT_EXPERIENCE,
                               DEB_EXPERIENCE, FIN_EXPERIENCE, DUREE_EXPERIENCE, DATE_DEMANDE_EXPERIENCE,
                               DATE_TRANSMISSION_RESULTAT, PRIORITE_EXPERIENCE, FREQUENCE_EXPERIENCE,
                               REPROGR_MAX_EXPERIENCE, COEFF_PRIX_PRIO_EXPERIENCE, VALEUR_BIAIS_A1,
                               VALEUR_BIAIS_A2, VALEUR_BIAIS_A3, MOYENNE_EXPERIENCE, ECART_TYPE_EXPERIENCE,
                               NB_RENOUVELLEMENT_EXPERIENCE)
        VALUES(seq_id_experience.NEXTVAL, id_technicien, id_chercheur, 'TypeExperience', 'EtatExperience',
               TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-01-10', 'YYYY-MM-DD'), 10,
               TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-01-10', 'YYYY-MM-DD'), 1, 
               DBMS_RANDOM.VALUE(1, 10), 1, 1, 0.5, 0.7, 0.2, 50, 5, 3);
    END LOOP;
    COMMIT;
END PEUPLE_EXPERIENCE;
/

EXECTURE PEUPLE_EXPERIENCE(30);
--LISTE ATTENTE
INSERT INTO LISTEATTENTE (ID_LISTE, NB_EXP_ATTENTE, EXPERIENCE, NB_EXP_DOUBLE) VALUES (1, 10, 1, 5);

--PLAQUE
INSERT INTO PLAQUE (ID_PLAQUE, ID_LOT, TYPE_PLAQUE, NB_EXPERIENCE_PLAQUE, ETAT_PLAQUE) VALUES (1, 1, 384, 50, 'EtatPlaque');

--GROUPESLOT
INSERT INTO GROUPESLOT (ID_GROUPE, ID_EXPERIENCE, ID_PLAQUE, MOYENNE_GROUPE, ECART_TYPE_GROUPE, VALIDITE_GROUPE) VALUES (1, 1, 1, 50, 5, 0);
INSERT INTO GROUPESLOT (ID_GROUPE, ID_EXPERIENCE, ID_PLAQUE, MOYENNE_GROUPE, ECART_TYPE_GROUPE, VALIDITE_GROUPE) VALUES (2, 1, 1, 50, 5, 0);

--SLOT
INSERT INTO SLOT (ID_SLOT, ID_GROUPE, COULEUR_SLOT, NUMERO_SLOT, POSITION_X_SLOT, POSITION_Y_SLOT, RM_SLOT, RD_SLOT, VM_SLOT, VD_SLOT, BM_SLOT, BD_SLOT, TM_SLOT, TD_SLOT) VALUES (1, 1, 'Couleur', 1, 10, 10, 1, 2, 3, 4, 5, 6, 7, 8);
INSERT INTO SLOT (ID_SLOT, ID_GROUPE, COULEUR_SLOT, NUMERO_SLOT, POSITION_X_SLOT, POSITION_Y_SLOT, RM_SLOT, RD_SLOT, VM_SLOT, VD_SLOT, BM_SLOT, BD_SLOT, TM_SLOT, TD_SLOT) VALUES (2, 1, 'Couleur', 2, 20, 20, 1, 2, 3, 4, 5, 6, 7, 8);
-- trigger d'automatisation pour ces deux la 

Commit;