/*==============================================================*/
/* TEST AJOUT EQUIPE      : ok                                  */
/*==============================================================*/
/*INSERT INTO EQUIPE (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE) 
VALUES (seq_id_equipe.NEXTVAL, 'Nouvelle Adresse', 5000);
INSERT INTO EQUIPE (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE) 
VALUES (seq_id_equipe.NEXTVAL, 'Nouvelle Adresse', 5070);
INSERT INTO EQUIPE (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE) 
VALUES (seq_id_equipe.NEXTVAL, 'Nouvelle Adresse', 5007);*/

/*==============================================================*/
/* Peuplement des tables                                 */
/*==============================================================*/
INSERT INTO FOURNISSEUR (ID_FOURNISSEUR, NOM_FOURNISSEUR) VALUES (1, 'NomFournisseur');
INSERT INTO STOCK (ID_STOCK, QUANTITE_P384, QUANTITE_P96, VOL_DERNIER_TRI_P384, VOL_DERNIER_TRI_P96) VALUES (1, 100, 100, 10, 10);
INSERT INTO LOT (ID_LOT, ID_STOCK, DATE_LIVRAISON_LOT, NB_PLAQUE) VALUES (1, 1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), 80);
INSERT INTO ACHETER (ID_FOURNISSEUR, ID_LOT) VALUES (1, 1);

INSERT INTO EQUIPE (ID_EQUIPE, ADRESSE_EQUIPE, SOLDE_EQUIPE) VALUES (1, 'AdresseEquipe', 5000);
INSERT INTO CHERCHEUR (ID_CHERCHEUR, ID_EQUIPE, NOM_CHERCHEUR, PRENOM_CHERCHEUR) VALUES (1, 1, 'NomChercheur', 'PrenomChercheur');
INSERT INTO FACTURE (ID_FACTURE, ID_EQUIPE, MONTANT_FACTURE, DATE_FACTURE) VALUES (1, 1, 1000, TO_DATE('2024-01-01', 'YYYY-MM-DD'));
INSERT INTO TECHNICIEN (ID_TECHNICIEN, ID_EQUIPE, NOM_TECHNICIEN, PRENOM_TECHNICIEN) VALUES (1, 1, 'NomTechnicien', 'PrenomTechnicien');

INSERT INTO EXPERIENCE (ID_EXPERIENCE, ID_LISTE, ID_TECHNICIEN, ID_CHERCHEUR, TYPE_EXPERIENCE, ETAT_EXPERIENCE, DEB_EXPERIENCE, FIN_EXPERIENCE, DUREE_EXPERIENCE, DATE_DEMANDE_EXPERIENCE, DATE_TRANSMISSION_RESULTAT, PRIORITE_EXPERIENCE, FREQUENCE_EXPERIENCE, REPROGR_MAX_EXPERIENCE, COEFF_PRIX_PRIO_EXPERIENCE, VALEUR_BIAIS_A1, VALEUR_BIAIS_A2, VALEUR_BIAIS_A3, MOYENNE_EXPERIENCE, ECART_TYPE_EXPERIENCE, NB_RENOUVELLEMENT_EXPERIENCE) VALUES (1, null, 1, 1, 'TypeExperience', 'EtatExperience', TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-01-10', 'YYYY-MM-DD'), 10, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-01-10', 'YYYY-MM-DD'), 1, 1, 1, 1, 0.5, 0.7, 0.2, 50, 5, 3);
INSERT INTO LISTEATTENTE (ID_LISTE, NB_EXP_ATTENTE, EXPERIENCE, NB_EXP_DOUBLE) VALUES (1, 10, 1, 5);
INSERT INTO APPAREIL (ID_APPAREIL, ID_LISTE, DISPO_APPAREIL, POSITION_APPAREIL) VALUES (1, 1, 0, 1);

INSERT INTO PLAQUE (ID_PLAQUE, ID_LOT, TYPE_PLAQUE, NB_EXPERIENCE_PLAQUE, ETAT_PLAQUE) VALUES (1, 1, 384, 50, 'EtatPlaque');
INSERT INTO GROUPESLOT (ID_GROUPE, ID_EXPERIENCE, ID_PLAQUE, MOYENNE_GROUPE, ECART_TYPE_GROUPE, VALIDITE_GROUPE) VALUES (1, 1, 1, 50, 5, 0);
INSERT INTO GROUPESLOT (ID_GROUPE, ID_EXPERIENCE, ID_PLAQUE, MOYENNE_GROUPE, ECART_TYPE_GROUPE, VALIDITE_GROUPE) VALUES (2, 1, 1, 50, 5, 0);
INSERT INTO SLOT (ID_SLOT, ID_GROUPE, COULEUR_SLOT, NUMERO_SLOT, POSITION_X_SLOT, POSITION_Y_SLOT, RM_SLOT, RD_SLOT, VM_SLOT, VD_SLOT, BM_SLOT, BD_SLOT, TM_SLOT, TD_SLOT) VALUES (1, 1, 'Couleur', 1, 10, 10, 1, 2, 3, 4, 5, 6, 7, 8);
INSERT INTO SLOT (ID_SLOT, ID_GROUPE, COULEUR_SLOT, NUMERO_SLOT, POSITION_X_SLOT, POSITION_Y_SLOT, RM_SLOT, RD_SLOT, VM_SLOT, VD_SLOT, BM_SLOT, BD_SLOT, TM_SLOT, TD_SLOT) VALUES (2, 1, 'Couleur', 2, 20, 20, 1, 2, 3, 4, 5, 6, 7, 8);

Commit;